### ISSUE TITLE
Bug na section dos testimonials

### ISSUE THREAD

**Issue by leandrobrunoo** [rocketseat-education/nlw-06-origin#3]
Encontrei um bug, ao passar pela _section_ do _testimonials_, abre uma barra no roda pé da página, e com isso quebra o layout e a usabilidade da pagina.
- Ao acessa a página em dispositivos moveis, o menu some.
- Ao passar pela _section_ usando um dispositivo maior, se eu for rolando a página com o mouse, quando chego na _section_, fica parado lá, impossibilitando a navegação na pagina.

Segue alguns print:

![Screenshot-01](https://user-images.githubusercontent.com/4401339/136636768-0674524a-5d21-4dff-8903-e93b94912d3d.png)
![Screenshot-02](https://user-images.githubusercontent.com/4401339/136636771-7b68d6cd-c9ae-4402-b4be-975fe185e98e.png)
![Screenshot-03](https://user-images.githubusercontent.com/4401339/136636772-ee5702fa-fd2b-4aec-acfe-e101a8b90692.png)

**Comment by leandrobrunoo** [comment]
I'm already working on the solution

**Comment by LucasMatsukuma** [comment]
Leandro, o problema já foi resolvido nesse PR: [https://github.com/rocketseat-education/nlw-06-origin/pull/5/commits/2de2a901d106204865df8a9feb2c2a2159c9487a](url).

**Comment by leandrobrunoo** [comment]
Eu mandei minha pequena contribuição lá.

**Comment by maykbrito** [comment]
Resolvido aqui 28fc15a 💜
