### ISSUE TITLE
SCROLL-BEHAVIOR E BARRA DE ROLAGEM LATERAL

### ISSUE THREAD

**Issue by wellington-bonjardim** [rocketseat-education/nlw-06-origin#6]
Boa noite, meu nome é Wellington e estou enfrentando dois problemas: 

PROBLEMA 1: Eu apliquei o comando abaixo para ter a rolagem suave mas não sei por qual motivo não está funcionando. Revi todas as linhas de código e não consegui encontrar o erro;
html {
  scroll-behavior: smooth;
}

PROBLEMA 2: Depois que inclui os três depoimentos, fiquei com uma barra de rolagem lateral que não consigo tirar por nada. Revi todas as linhas de código e não consegui encontrar o erro.

![image](https://user-images.githubusercontent.com/92733740/139509079-0df2cc5e-869a-47de-a02e-05e3b7ad9e18.png)

Alguém poderia me ajudar por gentileza?

**Comment by Guribeiro** [comment]
Olá, @wellington-bonjardim. Sobre o segundo problema, você consegue resolver apenas aplicando overflow-x: hidden, no container de testimonials;

`#testimonials {
  background: white;
  overflow-x: hidden;
}
`

Essa barra de rolagem lateral vai desaparecer.

Existe um PR aberto para corrigir essa quebra no layout em dispositivos pequenos.

**Comment by wellington-bonjardim** [comment]
Muito obrigado, Guribeiro! Me ajudou demais!

**Comment by wellington-bonjardim** [comment]
Muito obrigado, @Guribeiro ! Me ajudou demais!!

**Comment by maykbrito** [comment]
Resolvido aqui 28fc15a

**Comment by wellington-bonjardim** [comment]
Muito obrigado, mestre @maykbrito !

**Comment by victorchavesm** [comment]
> Boa noite, meu nome é Wellington e estou enfrentando dois problemas:
> 
> PROBLEMA 1: Eu apliquei o comando abaixo para ter a rolagem suave mas não sei por qual motivo não está funcionando. Revi todas as linhas de código e não consegui encontrar o erro; html { scroll-behavior: smooth; }
> 

Bem, aparentemente quando o @maykbrito fechou o tópico o problema 1 passou despercebido e já faz tanto tempo que capaz de você @wellington-bonjardim já ter até resolvido essa questão heheh
Também estava com esse mesmo problema, mas descobri que na verdade era o Smooth Scrolling da minha versão do Chrome que não tava habilitada. Resolvi da seguinte forma:
Cola esse endereço no teu Chrome

_**chrome://flags/#smooth-scrolling**_

e na caixinha de seleção do Smooth Scrolling altera pra "Enabled".
Aqui pelo menos resolvi assim.
