### ISSUE TITLE
Botão Agendar um Horário

### ISSUE THREAD

**Issue by Danny-ctrl** [rocketseat-education/nlw-06-origin#7]
Ola!

No projeto Original na linha    64 <a class="button" href="#">Agendar um horário</a>,não tem link para WhatsApp? Para onde esse botão direciona?

**Comment by danilo-vieira** [comment]
Olá @Danny-ctrl tudo bem?
De qual parte do projeto você está se referindo? Na NLW 06 - Origin, o botão para entrar em contato via WhatsApp [está aqui](https://github.com/rocketseat-education/nlw-06-origin/blob/28fc15a9ca84be859281f06840b8057ddb8be6d8/index.html#L234).

**Comment by Danny-ctrl** [comment]
> Olá @Danny-ctrl tudo bem? De qual parte do projeto você está se referindo? Na NLW 06 - Origin, o botão para entrar em contato via WhatsApp [está aqui](https://github.com/rocketseat-education/nlw-06-origin/blob/28fc15a9ca84be859281f06840b8057ddb8be6d8/index.html#L234).

Esse botão que vc marcou é o segundo,no inicio tem outro botão na linha 64

**Comment by danilo-vieira** [comment]
> > Olá @Danny-ctrl tudo bem? De qual parte do projeto você está se referindo? Na NLW 06 - Origin, o botão para entrar em contato via WhatsApp [está aqui](https://github.com/rocketseat-education/nlw-06-origin/blob/28fc15a9ca84be859281f06840b8057ddb8be6d8/index.html#L234).
> 
> Esse botão que vc marcou é o segundo,no inicio tem outro botão na linha 64

Para esse botão, você pode copiar o conteúdo do `href` desse que te mandei o link que vai funcionar perfeitamente 🤗

O código do botão ficaria assim:
```html
<a 
  class="button" 
  href="https://api.whatsapp.com/send?phone=+5511998456754&text=Oi! Gostaria de agendar um horário"
>
  Agendar um horário
</a>
```
